--- # Define episodic memories here
memories:
  - uuid: f0c903be-b00a-4c9d-b984-dc8d0af3c899
    summary: Brief description mainly used for documentation
    keywords: [list of, concepts, to reference]
    createTime: When the memory was created
    duration: Subjective duration of the given episode (optional)
    previous: A memory reference that immediately precedes this one (optional)
    next: A memory reference that immediately follows this one (optional)
    references:
      - List of memory references
      - that this one is tied to
      - in some other way
    content: >
      What is the memory about? This can be as simple or as detailed as necessary.
      The most effective episodic memory content includes information for all the
      senses involved, as well as thought and emotional content.

